# Generated by Django 5.0 on 2023-12-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='aurhor',
            new_name='aurthor',
        ),
    ]
